target1900: 1900 words
target1400: 1400 words
system: 2027 words
leap: 1935 words
teppeki: 2176 words

# First 50 words for each vocabulary:
target1900_sample = ['create', 'increase', 'improve', 'mean', 'own', 'include', 'consider', 'allow', 'suggest', 'produce', 'decide', 'offer', 'require', 'share', 'store', 'tend', 'concern', 'describe', 'involve', 'reduce', 'design', 'force', 'limit', 'bear', 'affect', 'deal', 'avoid', 'relate', 'realize', 'encourage', 'compare', 'measure', 'exist', 'mark', 'challenge', 'depend', 'object', 'demand', 'found', 'complete', 'idea', 'accord', 'company', 'interest', 'research', 'cause', 'reason', 'effect', 'influence', 'situation']
target1400_sample = ['believe', 'consider', 'expect', 'decide', 'allow', 'remember', 'worry', 'concern', 'suggest', 'explain', 'describe', 'improve', 'produce', 'create', 'provide', 'increase', 'grow', 'develop', 'rise', 'raise', 'follow', 'require', 'fill', 'support', 'share', 'face', 'touch', 'store', 'pay', 'deal', 'save', 'happen', 'occur', 'work', 'change', 'run', 'turn', 'return', 'stand', 'lie', 'brain', 'mind', 'language', 'thought', 'knowledge', 'skill', 'technology', 'culture', 'experience', 'result']
system_sample = ['follow', 'consider', 'increase', 'expect', 'decide', 'develop', 'provide', 'continue', 'include', 'remain', 'reach', 'allow', 'force', 'offer', 'realize', 'suggest', 'require', 'worry', 'wonder', 'cost', 'tend', 'depend', 'share', 'demand', 'support', 'hire', 'regard', 'base', 'improve', 'recognize', 'notice', 'suppose', 'raise', 'prefer', 'cheer', 'suffer', 'describe', 'prevent', 'reduce', 'mistake', 'prepare', 'encourage', 'prove', 'treat', 'establish', 'relate', 'compare', 'spread', 'refer', 'supply']
leap_sample = ['agree', 'oppose', 'advise', 'tip', 'discuss', 'blame', 'argue', 'claim', 'complain', 'offer', 'suggest', 'recommend', 'grateful', 'apologize', 'excuse', 'celebrate', 'admire', 'impress', 'award', 'describe', 'explain', 'communicate', 'express', 'promise', 'information', 'technology', 'research', 'material', 'artificial', 'electric', 'invent', 'discover', 'develop', 'skill', 'ability', 'talent', 'effort', 'practice', 'game', 'achieve', 'manage', 'improve', 'produce', 'create', 'establish', 'save', 'medicine', 'patient', 'condition', 'medical']
teppeki_sample = ['vital', 'vivid', 'revive', 'essential', 'indispensable', 'crucial', 'significance', 'consequence', 'matter', 'count', 'make a difference', 'trivial', 'trifle', 'common', 'ordinary', 'familiar', 'emphasize', 'stress', 'neglect', 'ignore', 'eminent', 'prominent', 'primary', 'tiny', 'slight', 'character', 'feature', 'trait', 'typical', 'unique', 'peculiar', 'particular', 'general', 'specify', 'distinguish', 'define', 'vague', 'obscure', 'ambiguous', 'obvious', 'evident', 'apparent', 'respect', 'aspect', 'detail', 'precise', 'accurate', 'structure', 'construct', 'destroy']
